# Setup
title:               mpma 
tagline:             'My corner of the internet'
description:         'A place for mathias expose his mind to the world, sorry world.'
url:                 https://www.mpma.se
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mathias Andreasen
  url:               https://mpma.se
  email:             mathiasandreasen91@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
